version: '3.1'
services:
  web_server:
    container_name: apache_web_server
    image: httpd:latest
    restart: always
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    depends_on:
      - reverse_proxy

  reverse_proxy:
    container_name: nginx_rproxy
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
